# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Synengco
title-bold: Synengco
title-normal: Giving you time
email: info@synengco.com
description: Giving you time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://synengco.com" # the base hostname & protocol for your site
author:
street_address: 28E Gladstone Rd
city: Highgate Hill
state: QLD
zip_code: 4101
country: Australia
location: Synengco,+Highgate+Hill,+Queensland
phone: +617 3229 3333
header-logo-white: logo_horizontal_white_small.png
header-logo-colour: logo_horizontal_colour_small.png

github-organisation: Synergetic-Engineering
git-repo: synengco-website

collections:
    sentientsystem-library:
        output: true


# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Blog settings
post-limit: 3 # post-preview
authors:
    sam:
        name: Sam Patterson
        image: sam.jpg
    don:
        name: Don Sands
        image: don.jpg

# Social settings
500px_url:
facebook_url: https://www.facebook.com/pages/Synengco-Pty-Ltd/473918309370363
github_url: https://github.com/Synergetic-Engineering
googleplus_url: https://plus.google.com/+SynengcoBrisbane
instagram_url:
linkedin_url: https://www.linkedin.com/company/synengco
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
logo: assets/images/logo_stacked_colour.png
google_site_verification: OvCpS4DYRKl4cch-bc2uLYgNOXbPwMGCHv9gFHBp_iM
google-analytics: UA-88744504-1

# Sass
sass:
  sass_dir: assets/sass
